package com.portfolio.designrag.service;

import jakarta.annotation.PostConstruct;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * Live JDBC corpus. Default uses embedded H2 (no paid key).
 * Profile {@code pgvector} points the datasource at Postgres (compose/Testcontainers).
 */
@Component
public class JdbcDesignCorpus implements DesignCorpus {
    private final JdbcTemplate jdbc;

    public JdbcDesignCorpus(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    @PostConstruct
    void schema() {
        jdbc.execute("""
                CREATE TABLE IF NOT EXISTS design_tokens (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  name VARCHAR(255) NOT NULL,
                  token_value VARCHAR(1024) NOT NULL,
                  notes VARCHAR(1024) DEFAULT ''
                )
                """);
    }

    @Override
    public int ingestCsv(String csv) {
        int added = 0;
        for (String line : csv.split("\\R")) {
            String trimmed = line.trim();
            if (trimmed.isEmpty() || trimmed.startsWith("token,") || trimmed.startsWith("#")) {
                continue;
            }
            String[] parts = trimmed.split(",", 3);
            if (parts.length < 2) {
                continue;
            }
            jdbc.update(
                    "INSERT INTO design_tokens(name, token_value, notes) VALUES (?,?,?)",
                    parts[0].trim(),
                    parts[1].trim(),
                    parts.length > 2 ? parts[2].trim() : "");
            added++;
        }
        return added;
    }

    @Override
    public List<TokenDoc> retrieve(String query, int limit) {
        String like = "%" + query.toLowerCase(Locale.ROOT) + "%";
        List<TokenDoc> hits = jdbc.query(
                """
                SELECT name, token_value, notes FROM design_tokens
                WHERE LOWER(name) LIKE ? OR LOWER(token_value) LIKE ? OR LOWER(notes) LIKE ?
                LIMIT ?
                """,
                (rs, i) -> new TokenDoc(rs.getString(1), rs.getString(2), rs.getString(3)),
                like, like, like, limit);
        if (hits.isEmpty()) {
            hits = jdbc.query(
                    "SELECT name, token_value, notes FROM design_tokens LIMIT ?",
                    (rs, i) -> new TokenDoc(rs.getString(1), rs.getString(2), rs.getString(3)),
                    limit);
        }
        return new ArrayList<>(hits);
    }

    @Override
    public int size() {
        Integer n = jdbc.queryForObject("SELECT COUNT(*) FROM design_tokens", Integer.class);
        return n == null ? 0 : n;
    }
}
