events {}
http {
  server {
    listen 8443 ssl;
    server_name localhost;
    ssl_certificate     /etc/certs/cert.pem;
    ssl_certificate_key /etc/certs/key.pem;
    location / {
      proxy_pass http://ai-edge-gateway:8080;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
