server:
  port: 8087

spring:
  application:
    name: app-factory

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
  info:
    env:
      enabled: false

info:
  app:
    name: app-factory

app:
  security:
    api-key: ${APP_FACTORY_API_KEY:}
